[build]
    command = "npm run build"
    publish = "dist"

[[redirects]]
  from = "/"
  to = "/fr-CA"
  status = 301
  force = false
  conditions = {Language = ["fr"]}

  [[redirects]]
  from = "/"
  to = "/en-CA"
  status = 301
  force = false
  conditions = {Language = ["en"]}