[build]
  command = "cd functions && npm i && cd .. && npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  framework = "eleventy"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
