[build]
  command = "cd functions && npm i && cd .. && npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  framework = "eleventy"

# For french
[[redirects]]
  from = "/"
  to = "/fr-CA"
  conditions = {Language = ["fr"], Country = ["CA"]}