[build]
  command = "cd functions && npm i && cd .. && npm run build"
  publish = "public"
  functions = "functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8080
  port = 8888
  publish = "public"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
